export const leftCol = [
  [
    {
      title: "Lunes a Viernes",
      schedules: [
        {
          hour: "06:00",
          discipline: "CrossFit",
          memberships: {
            seis: true,
            full: true,
            doce: true,
            ocho: true,
            am: false,
            valle: false,
            est: true,
          },
          span: 1,
        },
        {
          hour: "07:00",
          discipline: "CrossFit",
          memberships: {
            seis: false,
            full: true,
            doce: true,
            ocho: true,
            am: false,
            lunch: false,
            est: true,
          },
          span: 1,
        },
        {
          hour: "08:00",
          discipline: "CrossFit",
          memberships: {
            seis: false,
            full: true,
            doce: true,
            ocho: true,
            am: false,
            lunch: false,
            est: true,
          },
          span: 1,
        },
        {
          hour: "09:00",
          discipline: "CrossFit",
          memberships: {
            seis: false,
            full: true,
            doce: true,
            ocho: true,
            am: true,
            lunch: false,
            est: true,
            valle: true,
          },
          span: 1,
        },
        {
          hour: "10:00",
          discipline: "CrossFit",
          memberships: {
            seis: false,
            full: true,
            doce: true,
            ocho: true,
            am: true,
            lunch: false,
            est: true,
            valle: true,
          },
          span: 1,
        },
        {
          hour: "11:00",
          discipline: "CrossFit",
          memberships: {
            seis: false,
            full: true,
            doce: true,
            ocho: true,
            am: true,
            lunch: false,
            est: true,
            valle: true,
          },
          span: 1,
        },
        {
          hour: "12:00",
          discipline: "CrossFit",
          memberships: {
            seis: false,
            full: true,
            doce: true,
            ocho: true,
            am: true,
            lunch: false,
            est: true,
            valle: true,
          },
          span: 1,
        },
        {
          hour: "13:15",
          discipline: "CrossFit",
          memberships: {
            seis: false,
            full: true,
            doce: true,
            ocho: true,
            am: false,
            lunch: true,
            est: true,
            valle: true,
          },
          span: 1,
        },
        {
          hour: "16:00",
          discipline: "CrossFit",
          memberships: {
            seis: false,
            full: true,
            doce: true,
            ocho: true,
            am: false,
            lunch: true,
            est: true,
            valle: true,
          },
          span: 1,
        },
        {
          hour: "17:00",
          discipline: "CrossFit",
          memberships: {
            seis: false,
            full: true,
            doce: true,
            ocho: true,
            am: false,
            lunch: true,
            est: true,
            valle: true,
          },
          span: 1,
        },
        {
          hour: "18:00",
          discipline: "CrossFit",
          memberships: {
            seis: false,
            full: true,
            doce: true,
            ocho: true,
            am: false,
            lunch: false,
            est: true,
            valle: false,
          },
          span: 1,
        },
        {
          hour: "19:00",
          discipline: "CrossFit / Funcional",
          memberships: {
            seis: false,
            full: true,
            doce: true,
            ocho: true,
            am: false,
            lunch: false,
            est: false,
            valle: false,
          },
          span: 1,
        },
        {
          hour: "20:00",
          discipline: "CrossFit",
          memberships: {
            seis: false,
            full: true,
            doce: true,
            ocho: true,
            am: false,
            lunch: false,
            est: false,
            valle: false,
          },
          span: 1,
        },
        {
          hour: "21:00",
          discipline: "CrossFit",
          memberships: {
            seis: false,
            full: true,
            doce: true,
            ocho: true,
            am: false,
            lunch: false,
            est: false,
          },
          span: 1,
        },
      ],
    },
  ],
];

export const rightCol = [
  {
    title: "Lunes, miércoles y jueves",
    schedules: [
      {
        hour: "20:00",
        discipline: "Fundamentos",
        memberships: {
          seis: true,
          full: true,
          doce: true,
          ocho: true,
          am: true,
          lunch: true,
          est: true,
          valle: true,
        },
        span: 1,
      },
    ],
  },
  {
    title: "Martes y Viernes",
    schedules: [
      {
        hour: "18:00",
        discipline: "Barbell Club",
        memberships: {
          seis: true,
          full: true,
          doce: true,
          ocho: true,
          am: true,
          lunch: true,
          est: true,
        },
        span: 1,
      },
    ],
  },
  {
    title: "Sábados",
    schedules: [
      {
        hour: "08:45",
        discipline: "Barbell Club",
        memberships: {
          seis: true,
          full: true,
          doce: true,
          ocho: true,
          am: true,
          lunch: true,
          est: true,
          valle: true,
        },
        span: 1,
      },
      {
        hour: "10:45",
        discipline: "Barbell Club",
        memberships: {
          seis: true,
          full: true,
          doce: true,
          ocho: true,
          am: true,
          lunch: true,
          est: true,
          valle: true,
        },
        span: 1,
      },
      {
        hour: "11:00",
        discipline: "CrossFit",
        memberships: {
          seis: true,
          full: true,
          doce: true,
          ocho: true,
          am: true,
          lunch: true,
          est: true,
          valle: true,
        },
        span: 1,
      },
      {
        hour: "12:00",
        discipline: "CrossFit",
        memberships: {
          seis: true,
          full: true,
          doce: true,
          ocho: true,
          am: true,
          lunch: true,
          est: true,
          valle: true,
        },
        span: 1,
      },
      {
        noContent: true,
        hour: "",
        discipline: "",
        memberships: {
          seis: false,
          full: false,
          doce: false,
          ocho: false,
          am: false,
          lunch: false,
          est: false,
        },
        span: 6,
      },
    ],
  },
];

export const dataSchedules = {
  cols: [...leftCol, rightCol],
};
