const dataSchedules = [
  {
    forDays: "Lunes a Viernes",
    priority: 1,
    schedules: [
      {
        hour: "06:00",
        discipline: "CrossFit",
        memberships: {
          seis: true,
          full: false,
          doce: false,
          ocho: false,
          am: false,
          lunch: false,
          est: false,
        },
        span: 1,
      },
      {
        hour: "07:00",
        discipline: "CrossFit",
        memberships: {
          seis: false,
          full: true,
          doce: true,
          ocho: true,
          am: false,
          lunch: false,
          est: true,
        },
        span: 1,
      },
      {
        hour: "08:00",
        discipline: "CrossFit",
        memberships: {
          seis: false,
          full: true,
          doce: true,
          ocho: true,
          am: false,
          lunch: false,
          est: true,
        },
        span: 1,
      },
      {
        hour: "09:00",
        discipline: "CrossFit",
        memberships: {
          seis: false,
          full: true,
          doce: true,
          ocho: true,
          am: false,
          lunch: false,
          est: true,
        },
        span: 1,
      },
      {
        hour: "10:00",
        discipline: "CrossFit",
        memberships: {
          seis: false,
          full: true,
          doce: true,
          ocho: true,
          am: true,
          lunch: false,
          est: true,
        },
        span: 1,
      },
      {
        hour: "11:00",
        discipline: "CrossFit",
        memberships: {
          seis: false,
          full: true,
          doce: true,
          ocho: true,
          am: true,
          lunch: false,
          est: true,
        },
        span: 1,
      },
      {
        hour: "12:00",
        discipline: "CrossFit",
        memberships: {
          seis: false,
          full: true,
          doce: true,
          ocho: true,
          am: true,
          lunch: false,
          est: true,
        },
        span: 1,
      },
      {
        hour: "13:15",
        discipline: "CrossFit",
        memberships: {
          seis: false,
          full: true,
          doce: true,
          ocho: true,
          am: false,
          lunch: true,
          est: true,
        },
        span: 1,
      },
      {
        hour: "15:00",
        discipline: "CrossFit",
        memberships: {
          seis: false,
          full: true,
          doce: true,
          ocho: true,
          am: false,
          lunch: true,
          est: true,
        },
        span: 1,
      },
      {
        hour: "16:00",
        discipline: "CrossFit",
        memberships: {
          seis: false,
          full: true,
          doce: true,
          ocho: true,
          am: false,
          lunch: true,
          est: true,
        },
        span: 1,
      },
      {
        hour: "17:00",
        discipline: "CrossFit",
        memberships: {
          seis: false,
          full: true,
          doce: true,
          ocho: true,
          am: false,
          lunch: true,
          est: true,
        },
        span: 1,
      },
      {
        hour: "18:00",
        discipline: "CrossFit",
        memberships: {
          seis: false,
          full: true,
          doce: true,
          ocho: true,
          am: false,
          lunch: false,
          est: true,
        },
        span: 1,
      },
      {
        hour: "19:00",
        discipline: "CrossFit",
        memberships: {
          seis: false,
          full: true,
          doce: true,
          ocho: true,
          am: false,
          lunch: false,
          est: false,
        },
        span: 1,
      },
      {
        hour: "20:00",
        discipline: "CrossFit",
        memberships: {
          seis: false,
          full: true,
          doce: true,
          ocho: true,
          am: false,
          lunch: false,
          est: false,
        },
        span: 1,
      },
      {
        hour: "21:00",
        discipline: "CrossFit",
        memberships: {
          seis: false,
          full: true,
          doce: true,
          ocho: true,
          am: false,
          lunch: false,
          est: false,
        },
        span: 1,
      },
    ],
  },
  {
    forDays: "Sábados",
    priority: 2,
    schedules: [
      {
        noContent: true,
        hour: "",
        discipline: "",
        memberships: {
          seis: false,
          full: false,
          doce: false,
          ocho: false,
          am: false,
          lunch: false,
          est: false,
        },
        span: 3,
      },
      {
        hour: "08:30",
        discipline: "Barbell Club",
        memberships: {
          seis: true,
          full: true,
          doce: true,
          ocho: true,
          am: true,
          lunch: true,
          est: true,
        },
        span: 1,
      },
      {
        hour: "09:45",
        discipline: "Barbell Club",
        memberships: {
          seis: true,
          full: true,
          doce: true,
          ocho: true,
          am: true,
          lunch: true,
          est: true,
        },
        span: 1,
      },
      {
        hour: "11:00",
        discipline: "CrossFit",
        memberships: {
          seis: true,
          full: true,
          doce: true,
          ocho: true,
          am: true,
          lunch: true,
          est: true,
        },
        span: 1,
      },
      {
        hour: "12:00",
        discipline: "CrossFit",
        memberships: {
          seis: true,
          full: true,
          doce: true,
          ocho: true,
          am: true,
          lunch: true,
          est: true,
        },
        span: 1,
      },
      {
        noContent: true,
        hour: "",
        discipline: "",
        memberships: {
          seis: false,
          full: false,
          doce: false,
          ocho: false,
          am: false,
          lunch: false,
          est: false,
        },
        span: 8,
      },
    ],
  },
];

export default dataSchedules;
